/**
 * @file event.h
 * @brief Core engine event system (discrete input and platform events).
 *
 * The Wozzits event system represents **discrete state changes** produced by
 * the platform, engine, or game layer.
 *
 * Events are:
 * - frame-delivered (consumed per frame boundary)
 * - immutable after enqueue
 * - order-preserving per producer (MPSC queue semantics)
 * - not suitable for continuous or analog data
 *
 * This system is intentionally separate from InputState, which represents
 * a frame-sampled reconstruction of both events and continuous signals.
 */

#pragma once

#include <cstdint>
#include <wozzits/w_time.h>
#include <wozzits/mpsc_ring_buffer.h>

namespace wz::event
{
    /**
     * @brief Maximum number of events buffered per frame.
     *
     * If exceeded, events may be dropped depending on queue policy.
     * This is a real-time system constraint, not an error condition.
     */
    static constexpr size_t MAX_EVENTS = 4096;

    /**
     * @brief Discrete event generated by the platform, engine, or game.
     *
     * Events represent **state transitions**, not continuous values.
     * Examples:
     * - Key pressed / released
     * - Window resized
     * - Mouse button changes
     *
     * @note This is NOT an analog signal container.
     */
    struct Event
    {
        /**
         * @brief High-level grouping of event origin domain.
         */
        enum class Category
        {
            Input,      ///< User input devices (keyboard, mouse, controller)
            Window,     ///< Window system events (resize, focus, close)
            Controller, ///< Gamepad / controller events
            Mouse,      ///< Mouse-specific events
            VR          ///< VR device events
        };

        /**
         * @brief Origin of the event.
         */
        enum class Source
        {
            Platform, ///< OS / platform-generated event
            Engine,   ///< Engine-generated event
            Game      ///< Game/application-generated event
        };

        /**
         * @brief Specific event type.
         *
         * These represent discrete transitions only.
         */
        enum class Type : uint16_t
        {
            None,

            // Keyboard
            KeyPressDown,
            KeyPressUp,
            KeyHoldBegin,
            KeyHoldEnd,

            // Mouse
            MouseMove,
            MouseButton,

            // Window
            Resized,
            Closed,
            FocusGained,
            FocusLost,

            // Controller (discrete only)
            ControllerButton,
            ControllerAxis,

            // VR
            VREvent
        };

        /// Timestamp of event generation (platform or engine time).
        wz::time::Tick timestamp;

        Category category;

        /// Origin of event (platform, engine, or game).
        Source source;

        /// Event type identifier.
        Type type;

        uint32_t frame_index;  // NEW (critical)
        uint32_t frame_offset; // NEW (optional but powerful)
    };

    /**
     * @brief Global event queue (frame-driven, multi-producer).
     *
     * This queue is the primary transport mechanism between:
     * - OS/platform input layer
     * - engine subsystems
     * - game systems
     *
     * It is drained once per frame during the input build phase.
     */
    wz::core::MPSCRingBuffer<wz::event::Event, MAX_EVENTS> event_queue;
}